from typing import Optional

from pydantic import BaseModel, Field

from app.agents.schema_mapping.embedding_retriever import (
    SemanticCandidate,
    SemanticRetrievalResult,
)


# These thresholds are calibrated for the rerank_score produced by
# Step 2.11, not the original BGE combined score.

STRONG_SCORE_THRESHOLD = 0.70
STRONG_MARGIN_THRESHOLD = 0.20

MODERATE_SCORE_THRESHOLD = 0.50
MODERATE_MARGIN_THRESHOLD = 0.15

AMBIGUOUS_MARGIN_THRESHOLD = 0.08

MINIMUM_SCORE_THRESHOLD = 0.50


class SemanticEvaluationResult(BaseModel):
    """Evaluation of semantic schema candidates."""

    source_header: str
    normalized_header: str

    candidates: list[SemanticCandidate] = Field(default_factory=list)

    top_candidate: Optional[SemanticCandidate] = None
    second_candidate: Optional[SemanticCandidate] = None

    top_score: float = 0.0
    second_score: float = 0.0
    score_margin: float = 0.0

    category: str = "unresolved"

    evidence_summary: list[str] = Field(default_factory=list)

    retrieval_error: Optional[str] = None


def _classify_candidates(
    top_score: float,
    score_margin: float,
) -> str:
    """
    Classify the strength of semantic evidence.

    The thresholds are calibrated against the rerank score
    generated by Step 2.11.

    This classification is an evaluation signal, not a final
    schema-mapping decision.
    """

    # --------------------------------------------------------------
    # 1. Absolute evidence is too weak.
    #
    # A candidate that barely reaches the minimum threshold should
    # not become "ambiguous" merely because another candidate is
    # close to it.
    # --------------------------------------------------------------

    if top_score < MINIMUM_SCORE_THRESHOLD:
        return "weak"

    # --------------------------------------------------------------
    # 2. Strong evidence requires both:
    #    - high absolute score
    #    - clear separation from the second candidate
    # --------------------------------------------------------------

    if (
        top_score >= STRONG_SCORE_THRESHOLD
        and score_margin >= STRONG_MARGIN_THRESHOLD
    ):
        return "strong"

    # --------------------------------------------------------------
    # 3. Moderate evidence requires both:
    #    - meaningful absolute score
    #    - sufficient separation
    # --------------------------------------------------------------

    if (
        top_score >= MODERATE_SCORE_THRESHOLD
        and score_margin >= MODERATE_MARGIN_THRESHOLD
    ):
        return "moderate"

    # --------------------------------------------------------------
    # 4. If the candidates are close despite having meaningful
    #    evidence, classify the result as ambiguous.
    # --------------------------------------------------------------

    if score_margin < AMBIGUOUS_MARGIN_THRESHOLD:
        return "ambiguous"

    # --------------------------------------------------------------
    # 5. Remaining cases have some evidence but do not satisfy
    #    strong/moderate criteria.
    # --------------------------------------------------------------

    return "ambiguous"



def _build_evidence_summary(
    top_candidate: Optional[SemanticCandidate],
    second_candidate: Optional[SemanticCandidate],
    score_margin: float,
) -> list[str]:
    """Build human-readable evidence explanations."""

    reasons: list[str] = []

    if top_candidate is None:
        reasons.append("No semantic candidate was available.")
        return reasons

    reasons.append(
        f"Top candidate: {top_candidate.target_field} "
        f"with score {top_candidate.combined_score:.3f}."
    )

    reasons.append(
        f"Embedding similarity: "
        f"{top_candidate.embedding_similarity:.3f}."
    )

    reasons.append(
        f"Value evidence score: "
        f"{top_candidate.value_evidence_score:.3f}."
    )

    if top_candidate.evidence_reasons:
        reasons.extend(
            f"Value evidence: {reason}"
            for reason in top_candidate.evidence_reasons
        )

    if second_candidate is not None:
        reasons.append(
            f"Second candidate: {second_candidate.target_field} "
            f"with score "
            f"{second_candidate.combined_score:.3f}."
        )

        reasons.append(
            f"Candidate margin: {score_margin:.3f}."
        )

    return reasons


def evaluate_semantic_candidates(
    retrieval_result: SemanticRetrievalResult,
) -> SemanticEvaluationResult:
    """
    Evaluate semantic candidates returned by the retrieval/reranking
    pipeline.

    This function evaluates the strength and ambiguity of retrieved
    candidates. It does not make the final mapping decision.
    """

    candidates = list(retrieval_result.candidates)

    top_candidate: Optional[SemanticCandidate] = None
    second_candidate: Optional[SemanticCandidate] = None

    if candidates:
        top_candidate = candidates[0]

    if len(candidates) > 1:
        second_candidate = candidates[1]

    top_score = (
        top_candidate.combined_score
        if top_candidate is not None
        else 0.0
    )

    second_score = (
        second_candidate.combined_score
        if second_candidate is not None
        else 0.0
    )

    score_margin = round(
        max(0.0, top_score - second_score),
        6,
    )

    if retrieval_result.error:
        category = "unresolved"
    elif top_candidate is None:
        category = "unresolved"
    else:
        category = _classify_candidates(
            top_score=top_score,
            score_margin=score_margin,
        )

    evidence_summary = _build_evidence_summary(
        top_candidate=top_candidate,
        second_candidate=second_candidate,
        score_margin=score_margin,
    )

    return SemanticEvaluationResult(
        source_header=retrieval_result.source_header,
        normalized_header=retrieval_result.normalized_header,
        candidates=candidates,
        top_candidate=top_candidate,
        second_candidate=second_candidate,
        top_score=top_score,
        second_score=second_score,
        score_margin=score_margin,
        category=category,
        evidence_summary=evidence_summary,
        retrieval_error=retrieval_result.error,
    )