from collections import Counter
from typing import Any, Optional

import pandas as pd
from pydantic import BaseModel, Field

from app.agents.data_quality.config import SOV_REQUIRED_FIELDS
from app.agents.data_quality.issue_schema import (
    SEVERITY_RANK,
    IssueSeverity,
    QualityIssue,
)


class FieldQuality(BaseModel):
    """Per-field completeness and validity (FR-3)."""

    field: str

    present: bool

    total_rows: int = Field(ge=0)

    non_null_count: int = Field(ge=0)

    completeness_rate: float = Field(ge=0.0, le=1.0)

    issue_cell_count: int = Field(ge=0)

    # Share of non-empty cells with no issue. None when nothing to check.
    validity_rate: Optional[float] = Field(default=None, ge=0.0, le=1.0)


class QualityReport(BaseModel):
    """
    Aggregated deterministic data-quality report.

    This report summarizes QualityIssue objects without modifying
    the source DataFrame or the original issues.
    """

    total_issues: int = Field(ge=0)

    issues_by_severity: dict[str, int] = Field(
        default_factory=dict
    )

    issues_by_type: dict[str, int] = Field(
        default_factory=dict
    )

    issues_by_field: dict[str, int] = Field(
        default_factory=dict
    )

    critical_issue_count: int = Field(ge=0)

    high_issue_count: int = Field(ge=0)

    medium_issue_count: int = Field(ge=0)

    low_issue_count: int = Field(ge=0)

    human_review_required: bool

    quality_score: float = Field(
        ge=0.0,
        le=100.0,
    )

    issues: list[QualityIssue] = Field(
        default_factory=list
    )

    dataset_issue_count: int = Field(default=0, ge=0)

    # The fields below are only populated when aggregate() receives the
    # DataFrame the issues were detected on.

    field_quality: dict[str, FieldQuality] = Field(
        default_factory=dict
    )

    # row index -> fields with at least one issue on that row
    row_flags: dict[int, list[str]] = Field(
        default_factory=dict
    )

    # Severity-weighted share of clean cells across the 17 target
    # fields, 0-100. Unlike quality_score it does not collapse to 0 on
    # large files, so it is the score to show at intake.
    intake_quality_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=100.0,
    )


class QualityAggregator:
    """
    Aggregate deterministic QualityIssue objects into a QualityReport.

    Responsibilities:
    - count issues
    - group issues by severity
    - group issues by issue type
    - group issues by field
    - determine whether human review is required
    - calculate a deterministic quality score

    This class does not:
    - modify the source DataFrame
    - modify QualityIssue objects
    - approve issues
    - reject issues
    - resolve issues
    - automatically transform data
    """

    SEVERITY_PENALTIES = {
        IssueSeverity.CRITICAL: 25.0,
        IssueSeverity.HIGH: 15.0,
        IssueSeverity.MEDIUM: 5.0,
        IssueSeverity.LOW: 1.0,
    }

    # Weight of one affected cell in intake_quality_score.
    CELL_WEIGHTS = {
        IssueSeverity.CRITICAL: 1.0,
        IssueSeverity.HIGH: 1.0,
        IssueSeverity.MEDIUM: 0.5,
        IssueSeverity.LOW: 0.25,
    }

    def aggregate(
        self,
        issues: list[QualityIssue],
        dataframe: pd.DataFrame | None = None,
        target_fields: list[str] | None = None,
    ) -> QualityReport:
        """
        Aggregate a list of QualityIssue objects.

        Parameters
        ----------
        issues:
            Deterministic quality issues generated by Agent 3.

        Returns
        -------
        QualityReport
            Structured summary of the detected issues.
        """

        if issues is None:
            issues = []

        if not isinstance(issues, list):
            raise TypeError(
                "issues must be a list of QualityIssue objects"
            )

        self._validate_issues(issues)

        issues_by_severity = self._count_by_severity(
            issues
        )

        issues_by_type = self._count_by_type(
            issues
        )

        issues_by_field = self._count_by_field(
            issues
        )

        critical_issue_count = issues_by_severity.get(
            IssueSeverity.CRITICAL.value,
            0,
        )

        high_issue_count = issues_by_severity.get(
            IssueSeverity.HIGH.value,
            0,
        )

        medium_issue_count = issues_by_severity.get(
            IssueSeverity.MEDIUM.value,
            0,
        )

        low_issue_count = issues_by_severity.get(
            IssueSeverity.LOW.value,
            0,
        )

        human_review_required = (
            critical_issue_count > 0
            or high_issue_count > 0
        )

        quality_score = self._calculate_quality_score(
            issues
        )

        dataset_metrics: dict[str, Any] = {}

        if dataframe is not None:
            dataset_metrics = self._dataset_metrics(
                issues=issues,
                dataframe=dataframe,
                target_fields=target_fields or list(SOV_REQUIRED_FIELDS),
            )

        return QualityReport(
            total_issues=len(issues),
            issues_by_severity=issues_by_severity,
            issues_by_type=issues_by_type,
            issues_by_field=issues_by_field,
            critical_issue_count=critical_issue_count,
            high_issue_count=high_issue_count,
            medium_issue_count=medium_issue_count,
            low_issue_count=low_issue_count,
            human_review_required=human_review_required,
            quality_score=quality_score,
            issues=issues.copy(),
            dataset_issue_count=sum(
                1 for issue in issues if issue.row_index is None
            ),
            **dataset_metrics,
        )

    def _dataset_metrics(
        self,
        issues: list[QualityIssue],
        dataframe: pd.DataFrame,
        target_fields: list[str],
    ) -> dict[str, Any]:
        """
        Compute per-field completeness/validity, per-row flags and the
        intake quality score.

        Each (row, field) cell counts once, at its most severe issue.
        A dataset-level issue (for example an unmapped column) counts
        against every row of its field.
        """

        total_rows = int(len(dataframe))

        cell_severity: dict[tuple[int, str], IssueSeverity] = {}
        column_severity: dict[str, IssueSeverity] = {}
        row_flags: dict[int, set[str]] = {}

        def worse(
            current: IssueSeverity | None,
            new: IssueSeverity,
        ) -> IssueSeverity:
            if current is None or SEVERITY_RANK[new] > SEVERITY_RANK[current]:
                return new
            return current

        for issue in issues:
            if issue.row_index is None:
                column_severity[issue.source_field] = worse(
                    column_severity.get(issue.source_field),
                    issue.severity,
                )
                continue

            key = (issue.row_index, issue.source_field)
            cell_severity[key] = worse(cell_severity.get(key), issue.severity)
            row_flags.setdefault(issue.row_index, set()).add(
                issue.source_field
            )

        cells_by_field: dict[str, list[tuple[int, IssueSeverity]]] = {}

        for (row, field), severity in cell_severity.items():
            cells_by_field.setdefault(field, []).append((row, severity))

        field_quality: dict[str, FieldQuality] = {}
        penalty = 0.0

        for field in target_fields:
            present = field in dataframe.columns
            cells = cells_by_field.get(field, [])
            non_null = int(dataframe[field].notna().sum()) if present else 0

            invalid_non_null = (
                sum(
                    1
                    for row, _ in cells
                    if row in dataframe.index
                    and pd.notna(dataframe.at[row, field])
                )
                if present
                else 0
            )

            field_quality[field] = FieldQuality(
                field=field,
                present=present,
                total_rows=total_rows,
                non_null_count=non_null,
                completeness_rate=(
                    round(non_null / total_rows, 4) if total_rows else 0.0
                ),
                issue_cell_count=len(cells),
                validity_rate=(
                    round(1 - invalid_non_null / non_null, 4)
                    if non_null
                    else None
                ),
            )

            if field in column_severity:
                penalty += total_rows * self.CELL_WEIGHTS[
                    column_severity[field]
                ]
            else:
                penalty += sum(
                    self.CELL_WEIGHTS[severity] for _, severity in cells
                )

        # Row-level issues ("(row)", "TIV") are charged as one cell each.
        for field, cells in cells_by_field.items():
            if field not in target_fields:
                penalty += sum(
                    self.CELL_WEIGHTS[severity] for _, severity in cells
                )

        total_cells = total_rows * len(target_fields)

        if total_cells == 0:
            intake_score = 0.0 if issues else 100.0
        else:
            intake_score = 100.0 * max(0.0, 1 - penalty / total_cells)

        return {
            "field_quality": field_quality,
            "row_flags": {
                row: sorted(fields, key=str)
                for row, fields in sorted(row_flags.items())
            },
            "intake_quality_score": round(intake_score, 2),
        }

    def _validate_issues(
        self,
        issues: list[QualityIssue],
    ) -> None:
        """
        Validate that all supplied objects are QualityIssue instances.
        """

        for index, issue in enumerate(issues):

            if not isinstance(issue, QualityIssue):
                raise TypeError(
                    f"issues[{index}] must be a QualityIssue instance"
                )

    @staticmethod
    def _count_by_severity(
        issues: list[QualityIssue],
    ) -> dict[str, int]:
        """
        Count issues by severity.
        """

        counts = Counter(
            issue.severity.value
            for issue in issues
        )

        return dict(counts)

    @staticmethod
    def _count_by_type(
        issues: list[QualityIssue],
    ) -> dict[str, int]:
        """
        Count issues by issue type.
        """

        counts = Counter(
            issue.issue_type.value
            for issue in issues
        )

        return dict(counts)

    @staticmethod
    def _count_by_field(
        issues: list[QualityIssue],
    ) -> dict[str, int]:
        """
        Count issues by source field.

        The source field is used because it identifies the field
        where the validation issue originated.
        """

        counts = Counter(
            issue.source_field
            for issue in issues
        )

        return dict(counts)

    def _calculate_quality_score(
        self,
        issues: list[QualityIssue],
    ) -> float:
        """
        Calculate the deterministic quality score.

        Starting score:
            100

        Penalties:
            critical = 25
            high     = 15
            medium   = 5
            low      = 1

        Final score is bounded between 0 and 100.
        """

        penalty = 0.0

        for issue in issues:

            penalty += self.SEVERITY_PENALTIES.get(
                issue.severity,
                0.0,
            )

        score = 100.0 - penalty

        score = max(
            0.0,
            min(score, 100.0),
        )

        return round(score, 2)